# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6d503adb634c4cea1d5356bd750e549ae9769e061ce5844f5aa82507a5b3358d3acf66eb86dec6d47e9e0f6227fdf6c2bd65df8a26b60f0bdb5fbb9543aed98

test:
  secret_key_base: 218f9fe045780f430245c6a6440a9320039c663bab2eea10624d9b6a9f10be22598582b4fc9c5e9ea5d9a5bffdded587c41c275d494f89d8667084f6f1dd05cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
